# Organization-wide label definitions
# These can be synced to repositories using GitHub Actions
# Using prefix system inspired by opencloud-eu

# Component Labels (consistent light gray)
- name: "component:backstage"
  color: "DADADA"
  description: "Related to Backstage platform"

- name: "component:crossplane"
  color: "DADADA"
  description: "Related to Crossplane infrastructure"

- name: "component:kubernetes"
  color: "DADADA"
  description: "Kubernetes configuration and resources"

- name: "component:templates"
  color: "DADADA"
  description: "Service templates and scaffolding"

- name: "component:gitops"
  color: "DADADA"
  description: "CI/CD and GitOps workflows"

- name: "component:docs"
  color: "DADADA"
  description: "Documentation improvements"

# Area Labels (consistent light purple)
- name: "area:security"
  color: "E2BAFF"
  description: "Security-related issue"

- name: "area:performance"
  color: "E2BAFF"
  description: "Performance improvements"

- name: "area:dependencies"
  color: "E2BAFF"
  description: "Pull requests that update a dependency file"

- name: "area:tech-debt"
  color: "E2BAFF"
  description: "Technical debt and refactoring"

- name: "area:devops"
  color: "E2BAFF"
  description: "Build, deployment, infrastructure"

- name: "area:testing"
  color: "E2BAFF"
  description: "Testing and test infrastructure"

# Community Labels (consistent green)
- name: "help wanted"
  color: "36B37E"
  description: "Extra attention is needed"

- name: "good first issue"
  color: "36B37E"
  description: "Good for newcomers"